version: '3.9'

services:
  setup:
    profiles:
      - setup
    image: debian:stable-slim
    init: true
    entrypoint: /home/elasticsearch/setup.sh
    volumes:
      - ./bin/:/home/elasticsearch/
      - ./config/roles/:/home/elasticsearch/roles/
    env_file: .env
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    env_file: .env
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m

  logstash:
    image: docker.elastic.co/logstash/logstash:${ELK_VERSION}
    volumes:
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./pipeline:/usr/share/logstash/pipeline
    env_file: .env
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    env_file: .env
    depends_on:
      - elasticsearch

  app_1:
    build:
      context: app
    env_file: .env
    volumes:
      - ./config/filebeat_app_1.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - elasticsearch

  app_2:
    build:
      context: app
    env_file: .env
    volumes:
      - ./config/filebeat_app_2.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - elasticsearch
