---
node.name: elasticsearch
cluster.name: docker-cluster
network.host: 0.0.0.0
discovery.type: single-node
xpack.license.self_generated.type: trial
xpack.security.enabled: true
xpack.security.authc.api_key.enabled: true
