name: app_2

filebeat.inputs:
  - type: filestream
    id: app_2
    enabled: true
    paths:
      - /usr/share/filebeat/logs/*.log
    fields:
      type: text_logs

output.logstash:
  hosts: ["logstash:5044"]
  ttl: 0
